---
- name: Apply Kubernetes Services
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "{{ manifest_dir }}/grafana-service.yml"
    - "{{ manifest_dir }}/mysql-service.yml"
    - "{{ manifest_dir }}/prometheus-service.yml"
    - "{{ manifest_dir }}/argocd-service.yml"