services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
#    depends_on:
#      - backend
    networks:
      - Aira_shared_local_network

# Optionally define a network here if you want the frontend to link to the backend container by name:
networks:
  Aira_shared_local_network:
    external: true