Resources:
  GPTRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: gpt-request-queue.fifo
      FifoQueue: true
      ContentBasedDeduplication: false  # Since you're providing a MessageDeduplicationId
      VisibilityTimeout: 60               # In seconds
      ReceiveMessageWaitTimeSeconds: 20   # Enable long polling (20 seconds)
      MessageRetentionPeriod: 345600      # 4 days in seconds
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt GPTRequestDLQ.Arn
        maxReceiveCount: 3

  GPTRequestDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: gpt-request-dlq.fifo
      FifoQueue: true
      MessageRetentionPeriod: 1209600     # 14 days in seconds

  GPTResponseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: gpt-response-queue.fifo
      FifoQueue: true
      ContentBasedDeduplication: false
      VisibilityTimeout: 60
      ReceiveMessageWaitTimeSeconds: 20   # Enable long polling (20 seconds)
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt GPTResponseDLQ.Arn
        maxReceiveCount: 3

  GPTResponseDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: gpt-response-dlq.fifo
      FifoQueue: true
      MessageRetentionPeriod: 1209600     # 14 days in seconds