---
- name: Apply Kubernetes Persistent Volume Claims (PVC)
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "{{ manifest_dir }}/backup-pvc.yml"
    - "{{ manifest_dir }}/grafana-pvc.yml"
    - "{{ manifest_dir }}/mysql-pvc.yml"
    - "{{ manifest_dir }}/prometheus-pvc.yml"