---
- name: Apply Kubernetes StatefulSets
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "{{ manifest_dir }}/grafana-statefulset.yml"
    - "{{ manifest_dir }}/mysql-statefulset.yml"
    - "{{ manifest_dir }}/prometheus-statefulset.yml"