apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  admin.password: YWRtaW4xMjM0  # "admin1234"를 base64로 인코딩한 값
  admin.passwordMtime: MjAyNS0wMy0xMVQxNDoxMToxMFo=
  server.secretkey: bXlzZWNyZXRrZXk=