apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  root-password: YWRtaW5qYWtzaW0z  # 🔒 "password"를 base64로 인코딩한 값
  mysql-database: QWlyYQ==  # 🔒 "aira_db"를 base64로 인코딩한 값