name: Docker Image Vulnerability Scan with Trivy

on:
  push:
    branches: [ "dev_production" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    name: Scan Docker Image using Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          # Dockerfile이 루트에 있다고 가정합니다.
          docker build -t my-image:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-image:latest
          format: table