---
- name: Apply Kubernetes Deployments
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "{{ manifest_dir }}/jmeter-deployment.yml"
    - "{{ manifest_dir }}/argocd-deployment.yml"